import streamlit as st
import os
from dotenv import load_dotenv

# ============================================
# Load API Keys
# ============================================
load_dotenv()

if "GROQ_API_KEY" in st.secrets:
    os.environ["GROQ_API_KEY"] = st.secrets["GROQ_API_KEY"]
    os.environ["SERPAPI_API_KEY"] = st.secrets["SERPAPI_API_KEY"]
    os.environ["SENDER_EMAIL"] = st.secrets["SENDER_EMAIL"]
    os.environ["EMAIL_APP_PASSWORD"] = st.secrets["EMAIL_APP_PASSWORD"]

from agent import search_and_answer
from email_sender import send_email

# ============================================
# Page Configuration
# ============================================
st.set_page_config(
    page_title="AI Search & Email Agent",
    page_icon="🤖",
    layout="centered"
)

# ============================================
# Header
# ============================================
st.title("🤖 AI Search & Email Agent")
st.markdown("**Search the internet intelligently and receive results directly in your inbox.**")
st.divider()

# ============================================
# Search Input
# ============================================
st.subheader("🔍 Enter Your Query")
query = st.text_input(
    label="Search Query",
    placeholder="e.g. What are the latest developments in AI in 2025?",
    label_visibility="collapsed"
)

# ============================================
# Email Input - Optional
# ============================================
st.subheader("📧 Email Address (Optional)")
st.caption("Provide your email address if you would like the results sent to your inbox.")
email = st.text_input(
    label="Email Address",
    placeholder="e.g. example@gmail.com (optional)",
    label_visibility="collapsed"
)

st.divider()

# ============================================
# Search Button
# ============================================
if st.button("🔍 Search Now", type="primary", use_container_width=True):

    if not query:
        st.error("❌ Please enter a search query before proceeding.")
    else:
        # ----------------------------------------
        # Perform Search
        # ----------------------------------------
        with st.spinner("🔍 Searching the internet, please wait..."):
            answer = search_and_answer(query)

        st.success("✅ Search completed successfully!")
        st.divider()
        st.subheader("📋 Search Results:")
        st.write(answer)
        st.divider()

        # ----------------------------------------
        # Send Email if Provided
        # ----------------------------------------
        if email:
            with st.spinner("📧 Sending email, please wait..."):
                email_body = f"""
AI Search & Email Agent - Results

Your Query:
{query}

Answer:
{answer}

---
This email was automatically generated by the AI Search Agent.
                """

                success = send_email(
                    to_email=email,
                    subject=f"🤖 AI Search Result: {query[:50]}",
                    body=email_body
                )

            if success:
                st.success(f"📧 Results successfully sent to **{email}**")
            else:
                st.error("❌ Failed to send email. Please check your credentials.")
        else:
            st.info("ℹ️ No email provided — results are displayed above only.")

# ============================================
# Footer
# ============================================
st.divider()
st.markdown(
    "<center>Built with ❤️ using LangChain, LangGraph, Groq & Streamlit</center>",
    unsafe_allow_html=True
)